services:
  db:
    image: bitnami/postgresql:15
    container_name: ${CONTAINER_NAME}
    restart: always
    env_file:
      - .env  # Asegura que docker-compose cargue las variables
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./${VOLUME_NAME}:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
      build: .
      container_name: fastapi_app
      restart: always
      depends_on:
        - db
      ports:
        - "8000:8000"
      environment:
        DATABASE_URL: "postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@contenedor:5432/${POSTGRES_DB}"
      env_file:
        - .env